id: PFF833FC9
initial_creation_type: input
source_metadata:
  title: Bhagavadgītā-4comm with the commentaries of Śrīdhara, Madhusūdana, Viśvanātha
    and Baladeva
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Epic -- Mahābhārata
  data entry: Gaudiya Grantha Mandira
  contribution to GRETIL: Gaudiya Grantha Mandira
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T14:51:41.164978'
last_modified_at: '2022-03-09T14:51:41.164992'
